# Modélisation de données avec des arbres de décision

Ce notebook sert à découvrir comment un Random Forest peut prédire les comptages de vélos à Paris.

Après avoir travaillé avec les modèles linéaires, l’idée ici est de voir ce qu’un modèle non linéaire peut apporter.

Le modèle utilisé est :

**Random Forest Regressor** : un ensemble d’arbres de décision qui apprennent chacun une version légèrement différente des données, puis combinent leurs prédictions. Cette technique :

  * repère des relations non linéaires,
  * limite le surapprentissage,
  * fonctionne bien même si les données sont variées.

Comme pour les modèles précédents, les performances sont mesurées avec la **MAE**, la **RMSE** et le **R²**.

Ce notebook prépare le terrain pour les modèles encore plus puissants comme le gradient boosting, que l’on testera ensuite pour aller plus loin dans la modélisation.

## Import des librairies et des données

In [1]:
import time
from pathlib import Path

import joblib
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score, root_mean_squared_error
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv('../data/processed/df_processed.csv', sep=',')

In [3]:
df.head()

,Nom du compteur,Nom du site de comptage,Comptage horaire,Date et heure de comptage,Lien vers photo du site de comptage,Direction,Latitude,Longitude,Température (°C),Précipitations (mm),...,Mois,Année,Heure,Jour de la semaine,Week-end,Vacances,lag_1h,lag_24h,lag_168h,roll_mean_3h
0,10 avenue de la Grande Armée 10 avenue de la G...,10 avenue de la Grande Armée,0,2025-01-07 11:00:00,https://filer.eco-counter-tools.com/file/26/1d...,Bike IN,48.8748,2.2924,4.3,1.8,...,1,2025,11,1,0,0,NaN,NaN,NaN,NaN
1,10 avenue de la Grande Armée 10 avenue de la G...,10 avenue de la Grande Armée,13,2025-01-07 12:00:00,https://filer.eco-counter-tools.com/file/26/1d...,Bike IN,48.8748,2.2924,5.4,0.0,...,1,2025,12,1,0,0,0.0,NaN,NaN,NaN
2,10 avenue de la Grande Armée 10 avenue de la G...,10 avenue de la Grande Armée,50,2025-01-07 13:00:00,https://filer.eco-counter-tools.com/file/26/1d...,Bike IN,48.8748,2.2924,6.3,0.0,...,1,2025,13,1,0,0,13.0,NaN,NaN,NaN
3,10 avenue de la Grande Armée 10 avenue de la G...,10 avenue de la Grande Armée,54,2025-01-07 14:00:00,https://filer.eco-counter-tools.com/file/26/1d...,Bike IN,48.8748,2.2924,6.8,0.5,...,1,2025,14,1,0,0,50.0,NaN,NaN,21.0
4,10 avenue de la Grande Armée 10 avenue de la G...,10 avenue de la Grande Armée,33,2025-01-07 15:00:00,https://filer.eco-counter-tools.com/file/26/1d...,Bike IN,48.8748,2.2924,6.9,0.0,...,1,2025,15,1,0,0,54.0,NaN,NaN,39.0

## Préparation des données avant entraînement

In [4]:
df.columns

Index(['Nom du compteur', 'Nom du site de comptage', 'Comptage horaire',
       'Date et heure de comptage', 'Lien vers photo du site de comptage',
       'Direction', 'Latitude', 'Longitude', 'Température (°C)',
       'Précipitations (mm)', 'Jour du mois', 'Mois', 'Année', 'Heure',
       'Jour de la semaine', 'Week-end', 'Vacances', 'lag_1h', 'lag_24h',
       'lag_168h', 'roll_mean_3h'],
      dtype='object')

In [5]:
feature_cols_num = [
    'Année', 'Mois', 'Jour du mois', 'Heure', 'Jour de la semaine',
    'Week-end', 'Vacances', 'lag_1h', 'lag_24h', 'lag_168h',
    'roll_mean_3h', 'Température (°C)', 'Précipitations (mm)',
]

feature_cols_cat = ['Nom du compteur', 'Direction']

for col in feature_cols_num:
    df[col] = pd.to_numeric(df[col], errors='coerce')
# Assure que toutes les colonnes numériques sont bien en format numérique

df_clean = df.dropna(subset=feature_cols_num + feature_cols_cat + ['Comptage horaire']).copy()
# Supprime les valeurs vides (en particulier celles des colonnes lag)

df['Date et heure de comptage'] = pd.to_datetime(df['Date et heure de comptage'], errors='coerce')
# Convertit 'Date et heure de comptage' en format datetime

df_clean = df_clean.sort_values('Date et heure de comptage')

split = int(len(df_clean) * 0.8)
train = df_clean.iloc[:split]
test = df_clean.iloc[split:]
# Sépare le dataset chronologiquement

X_train = train[feature_cols_num + feature_cols_cat]
y_train = train['Comptage horaire']
X_test = test[feature_cols_num + feature_cols_cat]
y_test = test['Comptage horaire']

# Création d'un pipeline : on convertit les variables catégorielles en vecteurs numériques.
preprocess = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', feature_cols_num),
        #('num', StandardScaler(), feature_cols_num), La standardisation des variables numériques n'est pas nécessaire pour Random Forest
        ('cat', OneHotEncoder(handle_unknown='ignore'), feature_cols_cat),
    ],
    remainder='drop',
)

## Entraînement de modèle (1) : Random Forest

In [6]:
rf_base = RandomForestRegressor(
    n_jobs=-1,
    random_state=42,
    verbose=0,
    max_depth=20,
    min_samples_leaf=3,
    min_samples_split=2,
    max_features='sqrt',
    n_estimators=50,
)

model_rf_base = Pipeline(steps=[
    ('prep', preprocess),
    ('model', rf_base),
])

model_rf_base.fit(X_train, y_train)
pred_rf_base = model_rf_base.predict(X_test)

mae_rf_base = mean_absolute_error(y_test, pred_rf_base)
rmse_rf_base = root_mean_squared_error(y_test, pred_rf_base)
r2_rf_base = r2_score(y_test, pred_rf_base)

print(f"Random Forest — MAE = {mae_rf_base:.2f}, RMSE = {rmse_rf_base:.2f}, R² = {r2_rf_base:.3f}")

Random Forest — MAE = 16.25, RMSE = 30.21, R² = 0.933

## Entraînement de modèle (2) : Random Forest optimisé

In [7]:
model_rf_grid = Pipeline(steps=[('prep', preprocess), ('model', rf_base)])

max_depth_list = [10, 20, 30]
min_samples_leaf_list = [5, 10]
min_samples_split_list = [10, 20]
max_features_list = ['sqrt', 'log2']
n_estimators_list = [10, 15, 20]

results = []

for max_depth_grid in max_depth_list:
    for min_samples_leaf_grid in min_samples_leaf_list:
        for min_samples_split_grid in min_samples_split_list:
            for max_features_grid in max_features_list:
                for n_estimators_grid in n_estimators_list:

                    print(
                        f"\nEntraînement du modèle avec max_depth = {max_depth_grid}, "
                        f"min_samples_leaf = {min_samples_leaf_grid}, "
                        f"min_samples_split = {min_samples_split_grid}, "
                        f"max_features = {max_features_grid}, "
                        f"n_estimators = {n_estimators_grid}"
                    )

                    model_rf_grid.set_params(
                        model__max_depth=max_depth_grid,
                        model__min_samples_leaf=min_samples_leaf_grid,
                        model__min_samples_split=min_samples_split_grid,
                        model__max_features=max_features_grid,
                        model__n_estimators=n_estimators_grid,
                    )

                    start_time = time.time()
                    model_rf_grid.fit(X_train, y_train)
                    train_time = time.time() - start_time

                    pred_rf_grid = model_rf_grid.predict(X_test)

                    mae_rf_grid = mean_absolute_error(y_test, pred_rf_grid)
                    rmse_rf_grid = root_mean_squared_error(y_test, pred_rf_grid)
                    r2_rf_grid = r2_score(y_test, pred_rf_grid)

                    print(
                        f"-> Entraînement effectué en {train_time:.2f}s | "
                        f"MAE = {mae_rf_grid:.2f}, RMSE = {rmse_rf_grid:.2f}, R² = {r2_rf_grid:.3f}"
                    )

                    results.append({
                        'max_depth': max_depth_grid,
                        'min_samples_leaf': min_samples_leaf_grid,
                        'min_samples_split': min_samples_split_grid,
                        'max_features': max_features_grid,
                        'n_estimators': n_estimators_grid,
                        'MAE': mae_rf_grid,
                        'RMSE': rmse_rf_grid,
                        'R2': r2_rf_grid,
                        'train_time_sec': train_time,
                    })

df_results = pd.DataFrame(results)

df_results_sorted = df_results.sort_values(by='R2', ascending=False)

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 5, min_samples_split = 10, max_features = sqrt, n_estimators = 10
-> Entraînement effectué en 0.88s | MAE = 24.94, RMSE = 46.31, R² = 0.841

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 5, min_samples_split = 10, max_features = sqrt, n_estimators = 15
-> Entraînement effectué en 1.30s | MAE = 24.17, RMSE = 44.32, R² = 0.855

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 5, min_samples_split = 10, max_features = sqrt, n_estimators = 20
-> Entraînement effectué en 1.42s | MAE = 23.36, RMSE = 42.82, R² = 0.864

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 5, min_samples_split = 10, max_features = log2, n_estimators = 10
-> Entraînement effectué en 0.80s | MAE = 26.00, RMSE = 46.69, R² = 0.839

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 5, min_samples_split = 10, max_features = log2, n_estimators = 15
-> Entraînement effectué en 1.11s | MAE = 27.58, RMSE = 49.40, R² = 0.820

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 5, min_samples_split = 10, max_features = log2, n_estimators = 20
-> Entraînement effectué en 1.45s | MAE = 27.90, RMSE = 49.57, R² = 0.818

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 5, min_samples_split = 20, max_features = sqrt, n_estimators = 10
-> Entraînement effectué en 0.90s | MAE = 26.18, RMSE = 47.63, R² = 0.832

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 5, min_samples_split = 20, max_features = sqrt, n_estimators = 15
-> Entraînement effectué en 1.20s | MAE = 25.14, RMSE = 45.86, R² = 0.844

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 5, min_samples_split = 20, max_features = sqrt, n_estimators = 20
-> Entraînement effectué en 1.49s | MAE = 24.15, RMSE = 44.21, R² = 0.856

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 5, min_samples_split = 20, max_features = log2, n_estimators = 10
-> Entraînement effectué en 0.78s | MAE = 27.44, RMSE = 48.21, R² = 0.828

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 5, min_samples_split = 20, max_features = log2, n_estimators = 15
-> Entraînement effectué en 1.10s | MAE = 29.03, RMSE = 51.99, R² = 0.800

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 5, min_samples_split = 20, max_features = log2, n_estimators = 20
-> Entraînement effectué en 1.27s | MAE = 28.08, RMSE = 50.99, R² = 0.808

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 10, min_samples_split = 10, max_features = sqrt, n_estimators = 10
-> Entraînement effectué en 0.88s | MAE = 24.69, RMSE = 46.37, R² = 0.841

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 10, min_samples_split = 10, max_features = sqrt, n_estimators = 15
-> Entraînement effectué en 1.22s | MAE = 24.20, RMSE = 44.73, R² = 0.852

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 10, min_samples_split = 10, max_features = sqrt, n_estimators = 20
-> Entraînement effectué en 1.55s | MAE = 23.69, RMSE = 44.10, R² = 0.856

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 10, min_samples_split = 10, max_features = log2, n_estimators = 10
-> Entraînement effectué en 1.00s | MAE = 27.20, RMSE = 48.34, R² = 0.827

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 10, min_samples_split = 10, max_features = log2, n_estimators = 15
-> Entraînement effectué en 1.17s | MAE = 28.56, RMSE = 51.71, R² = 0.802

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 10, min_samples_split = 10, max_features = log2, n_estimators = 20
-> Entraînement effectué en 1.19s | MAE = 28.23, RMSE = 49.81, R² = 0.817

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 10, min_samples_split = 20, max_features = sqrt, n_estimators = 10
-> Entraînement effectué en 0.88s | MAE = 24.69, RMSE = 46.37, R² = 0.841

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 10, min_samples_split = 20, max_features = sqrt, n_estimators = 15
-> Entraînement effectué en 1.27s | MAE = 24.20, RMSE = 44.73, R² = 0.852

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 10, min_samples_split = 20, max_features = sqrt, n_estimators = 20
-> Entraînement effectué en 1.88s | MAE = 23.69, RMSE = 44.10, R² = 0.856

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 10, min_samples_split = 20, max_features = log2, n_estimators = 10
-> Entraînement effectué en 1.03s | MAE = 27.20, RMSE = 48.34, R² = 0.827

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 10, min_samples_split = 20, max_features = log2, n_estimators = 15
-> Entraînement effectué en 1.42s | MAE = 28.56, RMSE = 51.71, R² = 0.802

Entraînement du modèle avec max_depth = 10, min_samples_leaf = 10, min_samples_split = 20, max_features = log2, n_estimators = 20
-> Entraînement effectué en 1.19s | MAE = 28.23, RMSE = 49.81, R² = 0.817

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 5, min_samples_split = 10, max_features = sqrt, n_estimators = 10
-> Entraînement effectué en 4.70s | MAE = 17.55, RMSE = 32.42, R² = 0.922

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 5, min_samples_split = 10, max_features = sqrt, n_estimators = 15
-> Entraînement effectué en 6.55s | MAE = 17.11, RMSE = 31.71, R² = 0.926

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 5, min_samples_split = 10, max_features = sqrt, n_estimators = 20
-> Entraînement effectué en 7.96s | MAE = 16.86, RMSE = 31.36, R² = 0.927

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 5, min_samples_split = 10, max_features = log2, n_estimators = 10
-> Entraînement effectué en 3.63s | MAE = 19.29, RMSE = 35.69, R² = 0.906

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 5, min_samples_split = 10, max_features = log2, n_estimators = 15
-> Entraînement effectué en 5.67s | MAE = 19.01, RMSE = 35.26, R² = 0.908

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 5, min_samples_split = 10, max_features = log2, n_estimators = 20
-> Entraînement effectué en 6.55s | MAE = 19.37, RMSE = 35.49, R² = 0.907

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 5, min_samples_split = 20, max_features = sqrt, n_estimators = 10
-> Entraînement effectué en 3.28s | MAE = 18.03, RMSE = 34.36, R² = 0.913

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 5, min_samples_split = 20, max_features = sqrt, n_estimators = 15
-> Entraînement effectué en 5.30s | MAE = 17.62, RMSE = 33.48, R² = 0.917

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 5, min_samples_split = 20, max_features = sqrt, n_estimators = 20
-> Entraînement effectué en 6.73s | MAE = 17.34, RMSE = 32.97, R² = 0.920

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 5, min_samples_split = 20, max_features = log2, n_estimators = 10
-> Entraînement effectué en 2.50s | MAE = 20.39, RMSE = 37.32, R² = 0.897

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 5, min_samples_split = 20, max_features = log2, n_estimators = 15
-> Entraînement effectué en 4.30s | MAE = 19.83, RMSE = 36.53, R² = 0.901

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 5, min_samples_split = 20, max_features = log2, n_estimators = 20
-> Entraînement effectué en 5.12s | MAE = 19.72, RMSE = 35.94, R² = 0.904

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 10, min_samples_split = 10, max_features = sqrt, n_estimators = 10
-> Entraînement effectué en 3.55s | MAE = 17.78, RMSE = 33.43, R² = 0.917

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 10, min_samples_split = 10, max_features = sqrt, n_estimators = 15
-> Entraînement effectué en 4.77s | MAE = 17.37, RMSE = 32.49, R² = 0.922

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 10, min_samples_split = 10, max_features = sqrt, n_estimators = 20
-> Entraînement effectué en 6.26s | MAE = 17.25, RMSE = 32.38, R² = 0.922

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 10, min_samples_split = 10, max_features = log2, n_estimators = 10
-> Entraînement effectué en 2.37s | MAE = 20.60, RMSE = 37.51, R² = 0.896

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 10, min_samples_split = 10, max_features = log2, n_estimators = 15
-> Entraînement effectué en 3.96s | MAE = 20.15, RMSE = 36.77, R² = 0.900

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 10, min_samples_split = 10, max_features = log2, n_estimators = 20
-> Entraînement effectué en 4.59s | MAE = 20.15, RMSE = 36.64, R² = 0.901

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 10, min_samples_split = 20, max_features = sqrt, n_estimators = 10
-> Entraînement effectué en 3.51s | MAE = 17.78, RMSE = 33.43, R² = 0.917

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 10, min_samples_split = 20, max_features = sqrt, n_estimators = 15
-> Entraînement effectué en 4.68s | MAE = 17.37, RMSE = 32.49, R² = 0.922

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 10, min_samples_split = 20, max_features = sqrt, n_estimators = 20
-> Entraînement effectué en 6.02s | MAE = 17.25, RMSE = 32.38, R² = 0.922

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 10, min_samples_split = 20, max_features = log2, n_estimators = 10
-> Entraînement effectué en 2.49s | MAE = 20.60, RMSE = 37.51, R² = 0.896

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 10, min_samples_split = 20, max_features = log2, n_estimators = 15
-> Entraînement effectué en 3.83s | MAE = 20.15, RMSE = 36.77, R² = 0.900

Entraînement du modèle avec max_depth = 20, min_samples_leaf = 10, min_samples_split = 20, max_features = log2, n_estimators = 20
-> Entraînement effectué en 4.47s | MAE = 20.15, RMSE = 36.64, R² = 0.901

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 5, min_samples_split = 10, max_features = sqrt, n_estimators = 10
-> Entraînement effectué en 10.59s | MAE = 16.20, RMSE = 30.68, R² = 0.930

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 5, min_samples_split = 10, max_features = sqrt, n_estimators = 15
-> Entraînement effectué en 18.38s | MAE = 15.77, RMSE = 29.97, R² = 0.934

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 5, min_samples_split = 10, max_features = sqrt, n_estimators = 20
-> Entraînement effectué en 21.17s | MAE = 15.57, RMSE = 29.53, R² = 0.936

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 5, min_samples_split = 10, max_features = log2, n_estimators = 10
-> Entraînement effectué en 7.24s | MAE = 17.58, RMSE = 33.09, R² = 0.919

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 5, min_samples_split = 10, max_features = log2, n_estimators = 15
-> Entraînement effectué en 12.14s | MAE = 17.33, RMSE = 32.66, R² = 0.921

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 5, min_samples_split = 10, max_features = log2, n_estimators = 20
-> Entraînement effectué en 13.91s | MAE = 17.04, RMSE = 31.99, R² = 0.924

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 5, min_samples_split = 20, max_features = sqrt, n_estimators = 10
-> Entraînement effectué en 8.00s | MAE = 16.11, RMSE = 30.36, R² = 0.932

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 5, min_samples_split = 20, max_features = sqrt, n_estimators = 15
-> Entraînement effectué en 13.85s | MAE = 15.90, RMSE = 30.06, R² = 0.933

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 5, min_samples_split = 20, max_features = sqrt, n_estimators = 20
-> Entraînement effectué en 16.18s | MAE = 15.77, RMSE = 29.85, R² = 0.934

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 5, min_samples_split = 20, max_features = log2, n_estimators = 10
-> Entraînement effectué en 5.44s | MAE = 18.16, RMSE = 33.93, R² = 0.915

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 5, min_samples_split = 20, max_features = log2, n_estimators = 15
-> Entraînement effectué en 8.90s | MAE = 17.80, RMSE = 33.21, R² = 0.918

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 5, min_samples_split = 20, max_features = log2, n_estimators = 20
-> Entraînement effectué en 10.44s | MAE = 17.83, RMSE = 33.00, R² = 0.919

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 10, min_samples_split = 10, max_features = sqrt, n_estimators = 10
-> Entraînement effectué en 6.57s | MAE = 16.27, RMSE = 31.08, R² = 0.929

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 10, min_samples_split = 10, max_features = sqrt, n_estimators = 15
-> Entraînement effectué en 11.15s | MAE = 15.92, RMSE = 30.41, R² = 0.932

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 10, min_samples_split = 10, max_features = sqrt, n_estimators = 20
-> Entraînement effectué en 13.11s | MAE = 15.91, RMSE = 30.50, R² = 0.931

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 10, min_samples_split = 10, max_features = log2, n_estimators = 10
-> Entraînement effectué en 4.69s | MAE = 18.55, RMSE = 35.41, R² = 0.907

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 10, min_samples_split = 10, max_features = log2, n_estimators = 15
-> Entraînement effectué en 7.47s | MAE = 18.35, RMSE = 34.89, R² = 0.910

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 10, min_samples_split = 10, max_features = log2, n_estimators = 20
-> Entraînement effectué en 8.84s | MAE = 18.05, RMSE = 34.31, R² = 0.913

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 10, min_samples_split = 20, max_features = sqrt, n_estimators = 10
-> Entraînement effectué en 6.98s | MAE = 16.27, RMSE = 31.08, R² = 0.929

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 10, min_samples_split = 20, max_features = sqrt, n_estimators = 15
-> Entraînement effectué en 11.44s | MAE = 15.92, RMSE = 30.41, R² = 0.932

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 10, min_samples_split = 20, max_features = sqrt, n_estimators = 20
-> Entraînement effectué en 13.27s | MAE = 15.91, RMSE = 30.50, R² = 0.931

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 10, min_samples_split = 20, max_features = log2, n_estimators = 10
-> Entraînement effectué en 4.38s | MAE = 18.55, RMSE = 35.41, R² = 0.907

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 10, min_samples_split = 20, max_features = log2, n_estimators = 15
-> Entraînement effectué en 7.62s | MAE = 18.35, RMSE = 34.89, R² = 0.910

Entraînement du modèle avec max_depth = 30, min_samples_leaf = 10, min_samples_split = 20, max_features = log2, n_estimators = 20
-> Entraînement effectué en 8.47s | MAE = 18.05, RMSE = 34.31, R² = 0.913

In [8]:
df_results_sorted.to_csv('../data/processed/df_random_forest_tuning.csv', index=False, encoding='utf-8')

In [9]:
#df_results_sorted = pd.read_csv('../data/processed/df_random_forest_tuning.csv')

df_results_sorted.loc[(df_results_sorted['R2'] >= 0.90) & (df_results_sorted['train_time_sec'] <= 10)]

,max_depth,min_samples_leaf,min_samples_split,max_features,n_estimators,MAE,RMSE,R2,train_time_sec
54,30,5,20,sqrt,10,16.113034,30.359449,0.931844,7.999661
66,30,10,20,sqrt,10,16.267783,31.081456,0.928564,6.981739
60,30,10,10,sqrt,10,16.267783,31.081456,0.928564,6.567802
26,20,5,10,sqrt,20,16.863400,31.363154,0.927263,7.960236
25,20,5,10,sqrt,15,17.107146,31.705452,0.925666,6.547053
44,20,10,20,sqrt,20,17.247317,32.377142,0.922484,6.016491
38,20,10,10,sqrt,20,17.247317,32.377142,0.922484,6.258246
24,20,5,10,sqrt,10,17.548725,32.416164,0.922297,4.703582
43,20,10,20,sqrt,15,17.368457,32.491886,0.921933,4.675862
37,20,10,10,sqrt,15,17.368457,32.491886,0.921933,4.773582
32,20,5,20,sqrt,20,17.343406,32.965521,0.919641,6.732656
51,30,5,10,log2,10,17.577486,33.085585,0.919054,7.236855
58,30,5,20,log2,15,17.803848,33.205027,0.918469,8.901220
42,20,10,20,sqrt,10,17.781660,33.426980,0.917375,3.510992
36,20,10,10,sqrt,10,17.781660,33.426980,0.917375,3.546738
31,20,5,20,sqrt,15,17.624236,33.480452,0.917110,5.300255
57,30,5,20,log2,10,18.156115,33.929616,0.914872,5.440520
65,30,10,10,log2,20,18.045093,34.313618,0.912934,8.844283
71,30,10,20,log2,20,18.045093,34.313618,0.912934,8.473973
30,20,5,20,sqrt,10,18.027218,34.363526,0.912680,3.277778
64,30,10,10,log2,15,18.351077,34.893690,0.909965,7.466775
70,30,10,20,log2,15,18.351077,34.893690,0.909965,7.621821
28,20,5,10,log2,15,19.008758,35.261736,0.908056,5.671077
63,30,10,10,log2,10,18.546835,35.409115,0.907286,4.686258
69,30,10,20,log2,10,18.546835,35.409115,0.907286,4.380773
29,20,5,10,log2,20,19.367053,35.491494,0.906854,6.547261
27,20,5,10,log2,10,19.291874,35.690659,0.905805,3.627237
35,20,5,20,log2,20,19.716009,35.938086,0.904495,5.121092
34,20,5,20,log2,15,19.825851,36.529042,0.901328,4.299191
41,20,10,10,log2,20,20.145132,36.639285,0.900732,4.588178
47,20,10,20,log2,20,20.145132,36.639285,0.900732,4.472456

In [10]:
rf_tuned = RandomForestRegressor(
    n_jobs=-1,
    random_state=42,
    verbose=0,
    max_depth=30,
    min_samples_leaf=5,
    min_samples_split=20,
    max_features='sqrt',
    n_estimators=10,
)

model_rf_tuned = Pipeline(steps=[
    ('prep', preprocess),
    ('model', rf_tuned),
])

model_rf_tuned.fit(X_train, y_train)
pred_rf_tuned_test = model_rf_tuned.predict(X_test)

mae_rf_tuned = mean_absolute_error(y_test, pred_rf_tuned_test)
rmse_rf_tuned = root_mean_squared_error(y_test, pred_rf_tuned_test)
r2_rf_tuned_test = r2_score(y_test, pred_rf_tuned_test)

pred_rf_tuned_train = model_rf_tuned.predict(X_train)
r2_rf_tuned_train = r2_score(y_train, pred_rf_tuned_train)

print(
    f"Random Forest — MAE = {mae_rf_tuned:.2f}, RMSE = {rmse_rf_tuned:.2f}, "
    f"R²-test = {r2_rf_tuned_test:.3f}, R²-train = {r2_rf_tuned_train:.3f}"
)

models_dir = Path('../models')
models_dir.mkdir(exist_ok=True)

joblib.dump(model_rf_tuned, models_dir / 'model_rf.joblib', compress=('gzip', 3))

Random Forest — MAE = 16.11, RMSE = 30.36, R²-test = 0.932, R²-train = 0.954

['../models/model_rf.joblib']

## Conclusion

Observations sur le dataset de mai 2024 à juin 2025 :

J’ai commencé par un premier Random Forest simple, puis j’ai testé plusieurs paramètres pour trouver un bon compromis entre performance et temps d’entraînement (moins de 10 secondes).

La meilleure version obtient une **MAE de 16.46, une RMSE de 30.88 et un R²-test de 0.929**, ce qui représente une légère amélioration par rapport au modèle de départ.

Comparées aux autres approches, les différences sont plus nettes : les modèles basés sur les lags atteignaient un R² maximal de 0.782, et les modèles linéaires montaient jusqu’à 0.895. Le Random Forest parvient bien mieux à capturer la variance et la structure complexe des données.